version: '3.8'

services:
  app:
    build:
      context: "."
      dockerfile: "build/Dockerfile"
    ports:
      - "4545:4545" # Map the default port from the container to the host
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=4545