name: Docker Build and Push PocketCenter

on:
  push:
    branches: ["meta-*"]
  workflow_dispatch:

env:
  REGISTRY: cr.yandex/crpsa7b6pi9hgku83m9q
  IMAGE_NAME: pocket-center
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build_and_push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_API_KEY }}

      # - name: Extract Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build, Push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          provenance: false
          file: PocketCenter/build/run.Dockerfile
          context: PocketCenter
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Uncomment the following if you want to sign the Docker image
      # - name: Sign the published Docker image
      #   if: ${{ github.event_name != 'pull_request' }}
      #   env:
      #     TAGS: ${{ steps.meta.outputs.tags }}
      #     DIGEST: ${{ steps.build-and-push.outputs.digest }}
      #   run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  update-yc:
    runs-on: self-hosted
    needs: [build_and_push]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v2
        env:
          CR_REGISTRY: env.REGISTRY
          CR_REPOSITORY: my-cr-repo
          IMAGE_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: b1grqb7ja7b0e8uqu8np
          vm-name: yc-action-demo
          vm-service-account-id: ajej034gvpglqkemmvl0
          vm-cores: 2
          vm-memory: 2Gb
          vm-core-fraction: 100
          vm-subnet-id: e2lq92n6svpi4k2udj2q
          user-data-path: "./yandex-cloud/user-data.yaml"
          docker-compose-path: "./yandex-cloud/docker-compose.yc.yaml"
