name: Docker Build and Push PocketCenter

on:
  push:
    branches: ["meta-*"]
  paths:
    - PocketCenter/**
  workflow_dispatch:

env:
  REGISTRY: cr.yandex/crpsa7b6pi9hgku83m9q
  FACEBODY_IMAGE_NAME: facebody
  USERAUTH_IMAGE_NAME: userauth
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}${{ github.sha }}

jobs:
  build_and_push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        service:
          [
            { name: FaceBodyFeatureService, tag: facebody },
            { name: UserAuthSessionService, tag: userauth },
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_API_KEY }}

      - name: Build, Push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          provenance: false
          file: PocketCenter/${{ matrix.service.name }}/build/run.Dockerfile
          context: PocketCenter/${{ matrix.service.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ matrix.service.tag }}:${{ env.BRANCH_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-yc:
    runs-on: self-hosted
    needs: [build_and_push]
    steps:
      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v2
        env:
          FACEBODY_IMAGE_TAG: ${{ env.REGISTRY }}/${{ env.FACEBODY_IMAGE_NAME }}:${{ env.BRANCH_NAME }}
          USERAUTH_IMAGE_TAG: ${{ env.REGISTRY }}/${{ env.USERAUTH_IMAGE_NAME }}:${{ env.BRANCH_NAME }}
          YC_VM_USERNAME: ${{ vars.YC_VM_USERNAME }}
          YC_VM_SSH: ${{ vars.YC_VM_SSH }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          vm-name: pocket-center-testing
          vm-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          vm-cores: 2
          vm-memory: 2Gb
          vm-core-fraction: 50
          vm-subnet-id: ${{ secrets.YC_SUBNET_ID }}
          user-data-path: "./.github/workflows/yandex-cloud/user-data.yaml"
          docker-compose-path: "./.github/workflows/yandex-cloud/docker-compose.yc.yaml"
