name: Update log metrics systems

on:
  push:
    branches: ["meta-*"]
    paths:
      - .github/workflows/log-metric.yml
      - .github/workflows/yandex-cloud/docker-compose.log-metric.yc.yml
      - .github/workflows/yandex-cloud/user-data.yaml
  workflow_dispatch:

jobs:
  update-log-metric-on-yc:
    runs-on: self-hosted
    steps:
      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v2
        env:
          YC_VM_USERNAME: ${{ vars.YC_VM_USERNAME }}
          YC_VM_SSH: ${{ vars.YC_VM_SSH }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          vm-name: pocket-logs-metric
          vm-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          vm-cores: 2
          vm-memory: 1Gb
          vm-core-fraction: 20
          vm-subnet-id: ${{ secrets.YC_SUBNET_ID }}
          user-data-path: "./.github/workflows/yandex-cloud/user-data.yaml"
          docker-compose-path: "./.github/workflows/yandex-cloud/docker-compose.log-metric.yc.yml"
